TPMP="${XDG_DATA_HOME}/tmux/plugins"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${TPMP}"
set -g default-terminal tmux-256color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse off
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g focus-events on
set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'omerxx/tmux-sessionx'

# powerkit settings
set -g @powerkit_plugins "ssh,datetime"
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"
set -g @powerkit_separator_style "rounded"
set -g @powerkit_plugin_datetime_format "%Y-%m-%d %H:%M:%S"

# interactive theme selector: prefix + C-r
set -g @powerkit_theme_selector_key "C-r"

# override tmux-fzf's default C-F
TMUX_FZF_LAUNCH_KEY="="

# set sessionx's binding
set -g @sessionx-bind 'o'

set -g status-position top

# resize to match nvim
bind-key -T root 'M-h' resize-pane -L 1
bind-key -T root 'M-j' resize-pane -D 1
bind-key -T root 'M-k' resize-pane -U 1
bind-key -T root 'M-l' resize-pane -R 1

# restore clear screen
bind-key -T prefix 'C-l' send-keys 'C-l'

# restore sigquit
unbind -n C-\\

# vi yank bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# splits
bind | split-window -h
bind _ split-window -v
bind '"' split-window -v -c "#{pane_current_path}"
bind "%" split-window -h -c "#{pane_current_path}"

# OFF mode
bind -n M-o \
    set prefix None \;\
    set key-table off \;\
    set status-style "fg=red,bg=red"
bind -T off M-O \
    set -u prefix \;\
    set -u key-table \;\
    set -u status-style

if "test ! -d ${TPMP}/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm ${TPMP}/tpm && ${TPMP}/tpm/bin/install_plugins'"
run -b "${TPMP}/tpm/tpm"
